name: ci

on:
  push:
    # Trigger this workflow only on commits pushed to the main branch
    branches:
      - main

jobs:
  Test_plugins:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Test Helm
        uses: dagger/dagger-for-github@v2
        with:
          version: 0.2
          workdir: ./helm/test/test
          cmds: |
            project init
            project update
            project update https://github.com/disaster37/dagger-module@HEAD
            do test
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          http_proxy: ""
          https_proxy: ""
          no_proxy: ""
      
  Push_docker_images:
    needs: [Test_plugins]
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Push Openshift default image
        uses: dagger/dagger-for-github@v2
        with:
          version: 0.2
          workdir: ./openshift/test/ci
          cmds: |
            project init
            project update
            project update https://github.com/disaster37/dagger-module@HEAD
            do push
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          http_proxy: ""
          https_proxy: ""
          no_proxy: ""
      - name: Push Helm default image
        uses: dagger/dagger-for-github@v2
        with:
          version: 0.2
          workdir: ./helm/test/ci
          cmds: |
            project init
            project update
            project update https://github.com/disaster37/dagger-module@HEAD
            do push
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          http_proxy: ""
          https_proxy: ""
          no_proxy: ""